---
# tasks file for roles/k8s-master-role



- name: apt-udpate , apt upgrade
  apt:
    upgrade: yes
    update_cache: yes
  
- name: install some apps 
  apt:
    name: 
    - apt-transport-https
    - ca-certificates
    - wget 
    - curl
    - fail2ban
    - ufw 
    update_cache: yes
    state: present



- name: create keyring file 
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    recurse: yes



- name: Create containerd config file
  file:
    path: "/etc/modules-load.d/containerd.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
          overlay
          br_netfilter

- name: modprobe
  community.general.modprobe:
    name: 
      - overlay
      - br_netfilter
    state: present
    persistent: present

# - name: modprobe
#   shell: |
#           sudo modprobe overlay
#           sudo modprobe br_netfilter


- name: Set system configurations for Kubernetes networking
  file:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    state: "touch"

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/99-kubernetes-cri.conf"
    block: |
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
          net.bridge.bridge-nf-call-ip6tables = 1

- name: Apply new settings
  command: sudo sysctl --system

- name: apt-udpate , apt upgrade
  apt:
    upgrade: yes
    update_cache: yes

- name: install containerd
  apt: 
    name: containerd
    state: present

- name: disable swap
  shell: |
          sudo swapoff -a
          sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

- name: add apt key 
  shell: |
          curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -

- name: Add an apt signing key for Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Adding apt repository for Kubernetes
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

# - name: Create kubernetes repo file
#   file:
#     path: "/etc/apt/sources.list.d/kubernetes.list"
#     state: "touch"

# - name: Add K8s Source
#   blockinfile:
#     path: "/etc/apt/sources.list.d/kubernetes.list"
#     block: |
#           deb https://apt.kubernetes.io/ kubernetes-xenial main

- name: apt-udpate , apt upgrade
  apt:
    upgrade: yes
    update_cache: yes

- name: install versions of kubadm and kubectl and kubelet
  apt:
    name: 
      # - kubelet=1.20.1-00 
      # - kubeadm=1.20.1-00 
      - kubectl=1.20.1-00
    state: present

# - name: Hold kubeadm
#   ansible.builtin.dpkg_selections:
#     name: 
#     - kubeadm
#     - kubelet
#     - kubectl
#     selection: hold

- name: Prevent kubelet/kubeadm/kubectl from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop:
    - kubelet
    - kubeadm
    - kubectl